# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='cupos',
            field=models.CharField(max_length=60),
        ),
    ]
